parameters:
  - name: templateRepoAlias
    type: string

  - name: destinationPath
    type: string

  - name: variableGroup
    type: string

  - name: projectFolderName
    type: string

  - name: entrypointProjectName
    type: string

  - name: projectParentFolderPath
    type: string
    default: src

  - name: buildConfiguration
    type: string
    default: Release
    values:
      - Debug
      - Release

  - name: shouldTest
    type: boolean
    default: true

  - name: shouldPublish
    type: boolean
    default: true

  - name: shouldUpdateAppsettings
    type: boolean
    default: true

jobs:
  - job: BuildBackendJob
    displayName: Build Backend
    steps:
      - template: ../general/template-build-backend.yml
        parameters:
          projectFolderName: ${{ parameters.projectFolderName }}
          entrypointProjectName: ${{ parameters.entrypointProjectName }}
          projectParentFolderPath: ${{ parameters.projectParentFolderPath }}
          buildConfiguration: ${{ parameters.buildConfiguration }}
          shouldTest: ${{ parameters.shouldTest }}
          shouldPublish: ${{ parameters.shouldPublish }}

      - template: helpers/template-publish-artifact-to-temp-folder.yml
        parameters:
          destinationPath: ${{ parameters.destinationPath }}
          shouldPublish: ${{ parameters.shouldPublish }}

  - template: helpers/template-update-appsettings.yml
    parameters:
      dependsOn: BuildBackendJob
      templateRepoAlias: ${{ parameters.templateRepoAlias }}
      variableGroup: ${{ parameters.variableGroup }}
      destinationPath: ${{ parameters.destinationPath }}
      projectFolderName: ${{ parameters.projectFolderName }}
      shouldPublish: ${{ parameters.shouldPublish }}
      shouldUpdateAppsettings: ${{ parameters.shouldUpdateAppsettings }}
