parameters:
  - name: templateRepoAlias
    type: string
    default: templates

  - name: environment
    type: string

stages:
  - stage: ValidateRequestStage
    displayName: Validate Request
    jobs:
      - template: ../general/template-fail-on-condition.yml
        parameters:
          failCondition: >-
            and(
              eq(variables['isSourceMain'], true),
              eq(variables['Build.Reason'], 'Manual')
            )
          errorMessage: Manual releases from latest commit on main is not allowed. Use release tag instead.
          displayName: Fail on manual release from main
          jobNumber: 1

      - template: ../general/template-fail-on-condition.yml
        parameters:
          failCondition: >-
            and(
              eq(variables['isNewRelease'], false),
              eq(variables['environment'], 'prod')
            )
          errorMessage: Manual releases to production are not allowed.
          displayName: Fail on manual release to production
          jobNumber: 2

  - stage: GetPullRequestIdStage
    displayName: Get Pull Request Id
    condition: eq(variables['isNewRelease'], true)
    jobs:
      - template: template-get-pullrequest-id.yml
        parameters:
          templateRepoAlias: ${{ parameters.templateRepoAlias }}

  - stage: GetReleaseTagStage
    displayName: Get Release Tag
    dependsOn: GetPullRequestIdStage
    condition: >-
      and(
        eq(variables['isNewRelease'], true),
        not(or(failed(), canceled()))
      )
    variables:
      pullRequestId: $[ stageDependencies.GetPullRequestIdStage.Job.outputs['Task.PULLREQUEST_ID'] ]
    jobs:
      - template: template-get-valid-release-tag-from-pullrequest.yml
        parameters:
          templateRepoAlias: ${{ parameters.templateRepoAlias }}
          pullRequestId: $(pullRequestId)

  - stage: InitializeReleaseStage
    displayName: Initialize Release
    dependsOn:
      - GetReleaseTagStage
      - GetPullRequestIdStage
    condition: >-
      and(
        eq(variables['isNewRelease'], true),
        not(or(failed(), canceled()))
      )
    variables:
      releaseTag: $[ stageDependencies.GetReleaseTagStage.Job.outputs['Task.RELEASE_TAG'] ]
      pullRequestId: $[ stageDependencies.GetPullRequestIdStage.Job.outputs['Task.PULLREQUEST_ID'] ]
    jobs:
      - template: template-initialize-release.yml
        parameters:
          templateRepoAlias: ${{ parameters.templateRepoAlias }}
          pullRequestId: $(pullRequestId)
          tag: $(releaseTag)

  - stage: RunDeploymentPipelineStage
    displayName: Run Deployment
    dependsOn:
      - GetReleaseTagStage
      - InitializeReleaseStage
    condition: >-
      and(
        or(
          eq(variables['isSourceReleaseTag'], true),
          ne(variables['conditionReleaseTag'], '')
        ),
        not(or(failed(), canceled()))
      )
    variables:
      conditionReleaseTag: $[ dependencies.GetReleaseTagStage.outputs['Job.Task.RELEASE_TAG'] ]
      parameterReleaseTag: $[ stageDependencies.GetReleaseTagStage.Job.outputs['Task.RELEASE_TAG'] ]
    jobs:
      - template: template-run-pipeline.yml
        parameters:
          templateRepoAlias: ${{ parameters.templateRepoAlias }}
          environment: ${{ parameters.environment }}
          pipelineFilePath: pipelines/deployment.yml
          sourceTag: $(parameterReleaseTag)

  - stage: FinalizeReleaseStage
    displayName: Finalize Release
    dependsOn:
      - GetReleaseTagStage
      - GetPullRequestIdStage
      - RunDeploymentPipelineStage
    condition: eq(variables['isNewRelease'], true)
    variables:
      releaseTag: $[ stageDependencies.GetReleaseTagStage.Job.outputs['Task.RELEASE_TAG'] ]
      pullRequestId: $[ stageDependencies.GetPullRequestIdStage.Job.outputs['Task.PULLREQUEST_ID'] ]
      deploymentBuildId: $[ stageDependencies.RunDeploymentPipelineStage.Job.outputs['Task.PIPELINE_BUILD_ID'] ]
      deploymentFinishedDate: $[ stageDependencies.RunDeploymentPipelineStage.Job.outputs['Task.PIPELINE_BUILD_FINISHED_DATE'] ]
      deploymentJobResult: $[ stageDependencies.RunDeploymentPipelineStage.Job.result ]
    jobs:
      - template: template-finalize-release.yml
        parameters:
          templateRepoAlias: ${{ parameters.templateRepoAlias }}
          pullRequestId: $(pullRequestId)
          tag: $(releaseTag)
          deploymentBuildId: $(deploymentBuildId)
          deploymentFinishedDate: $(deploymentFinishedDate)
