parameters:
  - name: templateRepoAlias
    type: string

  - name: tag
    type: string

  - name: ticketIds
    type: string

jobs:
  - job: InitializeReleaseTicketsJob
    displayName: Initialize Release Tickets
    condition: not(or(failed(), canceled()))
    steps:
      - checkout: ${{ parameters.templateRepoAlias }}
        path: templates

      - task: PowerShell@2
        displayName: Initialize Release Tickets
        name: InitializeReleaseTicketsTask
        inputs:
          targetType: filePath
          filePath: $(Pipeline.Workspace)/templates/pipelines/release/scripts/initialize-release-tickets.ps1
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          TICKET_IDS: ${{ parameters.ticketIds }}
          TAG: ${{ parameters.tag }}
