parameters:
  - name: templateRepoAlias
    type: string

  - name: tag
    type: string

  - name: ticketIds
    type: string

jobs:
  - job: FinalizeSuccessfulReleaseTicketsJob
    displayName: Finalize Successful Release Tickets
    condition: startsWith(variables['deploymentJobResult'], 'Succeeded')
    steps:
      - checkout: ${{ parameters.templateRepoAlias }}
        path: templates

      - task: PowerShell@2
        displayName: Finalize Successful Release Tickets
        name: FinalizeSuccessfulReleaseTicketsTask
        inputs:
          targetType: filePath
          filePath: $(Pipeline.Workspace)/templates/pipelines/release/scripts/finalize-successful-release-tickets.ps1
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          TICKET_IDS: ${{ parameters.ticketIds }}
          TAG: ${{ parameters.tag }}
