parameters:
  - name: templateRepoAlias
    type: string

  - name: environment
    type: string

  - name: serviceConnection
    type: string

  - name: variableGroupName
    type: string

  - name: keyVaultName
    type: string

  - name: personalAccessToken
    type: string

jobs:
  - job: UpdateKeyVaultJob
    displayName: Update ${{ parameters.keyVaultName }}
    steps:
      - checkout: ${{ parameters.templateRepoAlias }}
        path: templates

      - task: AzureCLI@2
        displayName: Update Key Vault
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          scriptType: pscore
          scriptLocation: scriptPath
          scriptPath: $(Pipeline.Workspace)/templates/pipelines/azure/scripts/update-keyvault.ps1
          arguments: >
            -environment ${{ parameters.environment }}
            -variableGroupName ${{ parameters.variableGroupName }}
            -keyVaultName ${{ parameters.keyVaultName }}
            -personalAccessToken ${{ parameters.personalAccessToken }}
