parameters:
  - name: environment
    type: string

  - name: projectFolderName
    type: string

  - name: deploymentToken
    type: string

  - name: projectParentFolderPath
    type: string
    default: src

  - name: outputDirectory
    type: string
    default: wwwroot

  - name: apiDirectory
    type: string
    default: ''

jobs:
  - deployment: DeployStaticWebAppJob
    displayName: Deploy to ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureStaticWebApp@0
              displayName: Deploy Static Web App
              inputs:
                azure_static_web_apps_api_token: ${{ parameters.deploymentToken }}
                workingDirectory: $(Pipeline.Workspace)/${{ parameters.projectFolderName }}
                skip_app_build: true
                skip_api_build: true
                app_location: ${{ parameters.outputDirectory }}
                output_location: '.'
                ${{ if ne(parameters.apiDirectory, '') }}:
                  api_location: ${{ parameters.apiDirectory }}
