parameters:
  - name: environment
    type: string

  - name: projectFolderName
    type: string

  - name: projectParentFolderPath
    type: string
    default: src

  - name: outputDirectory
    type: string
    default: wwwroot

  - name: apiDirectory
    type: string
    default: ''

  - name: shouldTest
    type: boolean
    default: true

  - name: shouldLint
    type: boolean
    default: true

  - name: shouldPublish
    type: boolean
    default: true

jobs:
  - job: BuildFrontendJob
    displayName: Build Frontend
    steps:
      - template: ../general/template-build-frontend.yml
        parameters:
          environment: ${{ parameters.environment }}
          projectFolderName: ${{ parameters.projectFolderName }}
          projectParentFolderPath: ${{ parameters.projectParentFolderPath }}
          shouldTest: ${{ parameters.shouldTest }}
          shouldLint: ${{ parameters.shouldLint }}

      - task: CopyFiles@2
        displayName: Bundle wwwroot
        inputs:
          SourceFolder: ${{ parameters.projectParentFolderPath }}/${{ parameters.projectFolderName }}/${{ parameters.outputDirectory }}
          Contents: '**'
          TargetFolder: $(Build.ArtifactStagingDirectory)/deployment-bundle/${{ parameters.outputDirectory }}

      - task: CopyFiles@2
        displayName: Bundle api
        condition: |
          and(
            succeeded(),
            ne('${{ parameters.apiDirectory }}', '')
          )
        inputs:
          SourceFolder: ${{ parameters.projectParentFolderPath }}/${{ parameters.projectFolderName }}/${{ parameters.apiDirectory }}
          Contents: '**'
          TargetFolder: $(Build.ArtifactStagingDirectory)/deployment-bundle/${{ parameters.apiDirectory }}

      - task: PublishBuildArtifacts@1
        displayName: Publish Bundled Build Artifact
        condition: |
          and(
            succeeded(),
            eq(${{ parameters.shouldPublish }}, true)
          )
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)/deployment-bundle
          artifactName: ${{ parameters.projectFolderName }}
