parameters:
  - name: environment
    type: string

  - name: serviceConnection
    type: string

  - name: resourceGroup
    type: string

  - name: personalAccessToken
    type: string

  - name: entrypointScriptPath
    type: string
    default: iac/entrypoint.ps1

jobs:
  - deployment: DeployInfrastructureJob
    displayName: Deploy to ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              clean: true

            - task: AzureCLI@2
              displayName: Deploy ${{ parameters.resourceGroup }}
              name: DeployInfrastructureTask
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: pscore
                scriptLocation: scriptPath
                scriptPath: ${{ parameters.entrypointScriptPath }}
                arguments: >
                  -environment ${{ parameters.environment }}
                  -personalAccessToken ${{ parameters.personalAccessToken }}
